Enable automatic release flow
DolbyIO/comms-sdk-unreal pull request #128
Opened 2023-03-20 14:40 UTC by pczaj

2023-03-21 08:13 UTC, msobo1 commented on .github/workflows/release.yml
> +        version: ["4.27", "5.0"]
+ 5.1

2023-03-21 09:46 UTC, msobo1 commented on .github/workflows/release.yml
> +          ./.github/actions/upload_assets/upload_release_asset.sh ${{ env.UNREAL_PLUGIN_OUTPUT }}/DolbyIO_UnrealPlugin_${{ matrix.version }}_${{ env.BUILD_PLATFORM }}.zip
Zip file name is wrong. E.g. Build.DolbyIO.DolbyIO_UnrealPlugin_4.27_macos64.zip. It should be DolbyIO_UnrealPlugin_4.27_macos64.zip and after unzipping at lest the same. Perfect situation would be when after unzipping we could have just DolbyIO.

2023-03-22 15:59 UTC, kubaau requested changes

2023-03-22 15:59 UTC, kubaau commented on .github/workflows/release.yml
> +  CPP_SDK_TAG: "2.3.3"
2.4.0

2023-03-22 16:28 UTC, msobo1 approved these changes

2023-03-23 10:10 UTC, merged