Merge pull request #128 from DolbyIO/release_flow
DolbyIO/comms-sdk-unreal pull request #179
Opened 2023-05-25 13:38 UTC by pczaj

Enable automatic release flow

2023-05-25 14:12 UTC, msobo1 approved these changes

2023-05-25 14:26 UTC, kubaau requested changes

2023-05-25 14:26 UTC, kubaau commented on .github/workflows/release.yml
> +  CPP_SDK_TAG: "2.4.0"
This can't be right. I think you want to merge into branch 1.0 and then CPP_SDK_TAG must be 2.3 and UE versions below should not include 5.1.

2023-05-25 15:05 UTC, kubaau requested changes

2023-05-25 15:05 UTC, kubaau commented on .github/workflows/release.yml
> +        version: ["4.27", "5.0", "5.1"]
If I understand correctly, you want to enable the same flow as currently on main also on 1.0. But the pull request is still to go into main and I think what you want to do is have the .github folder on 1.0 exactly the same as on main except CPP_SDK_TAG 2.3.3 and version 4.27, 5.0 (not 5.1).

2023-05-26 10:09 UTC, msobo1 approved these changes

2023-05-26 10:23 UTC, kubaau requested changes

2023-05-26 10:23 UTC, kubaau commented on .github/workflows/release.yml
> +        version: ["4.27", "5.0", "5.1"]
I see 5.1 in build-windows :)

2023-05-26 12:08 UTC, kubaau approved these changes

2023-05-26 12:08 UTC, merged